### ISSUE TITLE
Off Timer

### ISSUE THREAD

**Issue by TwelveK** [brainfoolong/gpio-webinterface#1]
How would I implement a timer to turn a switch off after a period of time?

**Comment by brainfoolong** [comment]
This is not supported by this interface.

**Comment by mani6464** [comment]
This feature would be nice.
That you can trigger the output for 2-3 seconds (adjustable)
Can it be implemantet or not possible??

Thanks

**Comment by brainfoolong** [comment]
It's pretty much the same, it's not supported but theoretically possible to implement.
