### ISSUE TITLE
Doesn't work on Raspbian Stretch

### ISSUE THREAD

**Issue by martinallnet** [brainfoolong/gpio-webinterface#2]
I have installed the code at pi-userdir and i can't switch the status of the GPIO.
I use php7.0 and a Raspbian Stretch with wiringPi 2.44+1.

**Comment by brainfoolong** [comment]
Do you have tested if it work in pure command line, with for example `gpio PIN MODE` and `gpio write 1`

**Comment by martinallnet** [comment]
works with gpio -g and the number, which numbers are used?
EDIT: Use the wrong number, with the correct number it works.

**Comment by brainfoolong** [comment]
It depends what you configure in the interface.

The interface do nothing more than you can do manually via cli.
It uses the default executable `/usr/local/bin/gpio`

All other stuff like, PIN and MODE you have to define in the settings interface.

**Comment by martinallnet** [comment]
Another question:
Is it possible to use PWM as a slider for LED brightness control?

**Comment by brainfoolong** [comment]
No PWMN slider integrated, sry.

**Comment by martinallnet** [comment]
I also need for a 433 Mhz control a feature, the switch is only a button that activates the gpio for a small time and i need to use 2 gpios with one button.
Is this possible?

**Comment by brainfoolong** [comment]
Also, no, sry. I suggest you to use another, more feature rich application. I don't know any, but this is obviously no app that fit your needs.
